{% set data = load_setup_py_data() %}

package:
  name: ema_workbench
  version: {{ data.get('version') }}

source:
  path: ../

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools_scm
    - pyscaffold
    - sphinx
    - ipykernel
    - nbsphinx
    - numpy
    - scipy
    - pandas
    - ipython
    - ipyparallel
    - jupyter
    - scikit-learn
    - seaborn
    - matplotlib
    - pyzmq
    - platypus-opt
    - altair
    - pydot
    - dask
    - distributed
    - salib

build:
  noarch: python

test:
  imports:
    - ema_workbench

about:
  home: https://github.com/jpn--/EMAworkbench
  license_file: LICENSE.md